services:
  mongodb:
    image: mongo:6.0
    container_name: glabitai_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "'db.adminCommand({ping: 1})'", "--quiet"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        INSTALL_UV: "true" # Pass argument to Dockerfile to install uv
    container_name: glabitai_backend
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/glabitai_db?authSource=admin
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      GROQ_API_KEY: ${GROQ_API_KEY}
      # Add other environment variables as needed
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - backend_venv:/app/.venv

volumes:
  mongodb_data:
  backend_venv:
